export enum ZONE_REGION_LABELS {
  MONTREAL = "Montréal",
  LONGUEUIL_ET_ALENTOURS = "Longueuil et alentours",
  LAVAL_ET_ALENTOURS = "Laval et alentours",
  REPENTIGNY_ET_ALENTOURS = "Repentigny et alentours",
}

export enum ZONE_AREA_LABELS {
  PLATEAU_MONT_ROYAL = "Plateau-Mont-Royal",
  ROSEMONT = "Rosemont",
  AHUNTSIC = "Ahuntsic",
  SAINT_LEONARD = "Saint-Léonard",
  VILLE_MARIE = "Ville-Marie",
  BROSSARD = "Brossard",
  SAINT_HUBERT = "Saint-Hubert",
  BOUCHERVILLE = "Boucherville",
  SAINT_LAMBERT = "Saint-Lambert",
  GREENFIELD_PARK = "Greenfield Park",
  CHOMEDEY = "Chomedey",
  SAINTE_ROSE = "Sainte-Rose",
  VIMONT = "Vimont",
  PONT_VIAU = "Pont-Viau",
  DUVERNAY = "Duvernay",
  LASSOMPTION = "L'Assomption",
  LE_GARDEUR = "Le Gardeur",
  CHARLEMAGNE = "Charlemagne",
  MASCOUCHE = "Mascouche",
  TERREBONNE = "Terrebonne",
}

export enum AREA_SERVED_LABELS {
  MONTREAL = "Montréal",
  LAVAL = "Laval",
  LONGUEUIL = "Longueuil",
  SAINTE_JULIE = "Sainte-Julie",
  RIVE_SUD = "Rive-Sud",
  REPENTIGNY = "Repentigny",
}

export type ServiceZone = {
  region: ZONE_REGION_LABELS;
  areas: ZONE_AREA_LABELS[];
};

export const SERVICE_ZONES: ServiceZone[] = [
  {
    region: ZONE_REGION_LABELS.MONTREAL,
    areas: [
      ZONE_AREA_LABELS.PLATEAU_MONT_ROYAL,
      ZONE_AREA_LABELS.ROSEMONT,
      ZONE_AREA_LABELS.AHUNTSIC,
      ZONE_AREA_LABELS.SAINT_LEONARD,
      ZONE_AREA_LABELS.VILLE_MARIE,
    ],
  },
  {
    region: ZONE_REGION_LABELS.LONGUEUIL_ET_ALENTOURS,
    areas: [
      ZONE_AREA_LABELS.BROSSARD,
      ZONE_AREA_LABELS.SAINT_HUBERT,
      ZONE_AREA_LABELS.BOUCHERVILLE,
      ZONE_AREA_LABELS.SAINT_LAMBERT,
      ZONE_AREA_LABELS.GREENFIELD_PARK,
    ],
  },
  {
    region: ZONE_REGION_LABELS.LAVAL_ET_ALENTOURS,
    areas: [
      ZONE_AREA_LABELS.CHOMEDEY,
      ZONE_AREA_LABELS.SAINTE_ROSE,
      ZONE_AREA_LABELS.VIMONT,
      ZONE_AREA_LABELS.PONT_VIAU,
      ZONE_AREA_LABELS.DUVERNAY,
    ],
  },
  {
    region: ZONE_REGION_LABELS.REPENTIGNY_ET_ALENTOURS,
    areas: [
      ZONE_AREA_LABELS.LASSOMPTION,
      ZONE_AREA_LABELS.LE_GARDEUR,
      ZONE_AREA_LABELS.CHARLEMAGNE,
      ZONE_AREA_LABELS.MASCOUCHE,
      ZONE_AREA_LABELS.TERREBONNE,
    ],
  },
];

export const STRUCTURED_DATA_AREA_SERVED: AREA_SERVED_LABELS[] = [
  AREA_SERVED_LABELS.MONTREAL,
  AREA_SERVED_LABELS.LAVAL,
  AREA_SERVED_LABELS.LONGUEUIL,
  AREA_SERVED_LABELS.RIVE_SUD,
  AREA_SERVED_LABELS.REPENTIGNY,
];

export const CONTACT_AREA_SERVED_LINE_1 = `${AREA_SERVED_LABELS.MONTREAL}, ${AREA_SERVED_LABELS.LAVAL}, ${AREA_SERVED_LABELS.LONGUEUIL}, ${AREA_SERVED_LABELS.SAINTE_JULIE}`;
export const CONTACT_AREA_SERVED_LINE_2 = `${AREA_SERVED_LABELS.RIVE_SUD} et les environs`;

export const CONTACT_AREA_SERVED_SUMMARY = `${AREA_SERVED_LABELS.MONTREAL}, ${AREA_SERVED_LABELS.LAVAL}, ${AREA_SERVED_LABELS.LONGUEUIL}, ${AREA_SERVED_LABELS.SAINTE_JULIE} et la ${AREA_SERVED_LABELS.RIVE_SUD}`;
