import { ROUTE_PATHS } from "@/consts/navigation";

export enum ZONE_REGION_LABELS {
  MONTREAL = "Montréal",
  LONGUEUIL_ET_ALENTOURS = "Longueuil et alentours",
  LAVAL_ET_ALENTOURS = "Laval et alentours",
  REPENTIGNY_ET_ALENTOURS = "Repentigny et alentours",
}

export enum AREA_SERVED_LABELS {
  MONTREAL = "Montréal",
  LAVAL = "Laval",
  LONGUEUIL = "Longueuil",
  SAINTE_JULIE = "Sainte-Julie",
  RIVE_SUD = "Rive-Sud",
  REPENTIGNY = "Repentigny",
}

export enum ZONE_AREA_LABELS {
  PLATEAU_MONT_ROYAL = "Plateau-Mont-Royal",
  ROSEMONT = "Rosemont",
  AHUNTSIC = "Ahuntsic",
  SAINT_LEONARD = "Saint-Léonard",
  VILLE_MARIE = "Ville-Marie",
  BROSSARD = "Brossard",
  SAINT_HUBERT = "Saint-Hubert",
  BOUCHERVILLE = "Boucherville",
  SAINT_LAMBERT = "Saint-Lambert",
  GREENFIELD_PARK = "Greenfield Park",
  CHOMEDEY = "Chomedey",
  SAINTE_ROSE = "Sainte-Rose",
  VIMONT = "Vimont",
  PONT_VIAU = "Pont-Viau",
  DUVERNAY = "Duvernay",
  LASSOMPTION = "L'Assomption",
  LE_GARDEUR = "Le Gardeur",
  CHARLEMAGNE = "Charlemagne",
  MASCOUCHE = "Mascouche",
  TERREBONNE = "Terrebonne",
}

export type ServiceZone = {
  region: ZONE_REGION_LABELS;
  areas: ZONE_AREA_LABELS[];
};

export const SERVICE_ZONES: ServiceZone[] = [
  {
    region: ZONE_REGION_LABELS.MONTREAL,
    areas: [
      ZONE_AREA_LABELS.PLATEAU_MONT_ROYAL,
      ZONE_AREA_LABELS.ROSEMONT,
      ZONE_AREA_LABELS.AHUNTSIC,
      ZONE_AREA_LABELS.SAINT_LEONARD,
      ZONE_AREA_LABELS.VILLE_MARIE,
    ],
  },
  {
    region: ZONE_REGION_LABELS.LONGUEUIL_ET_ALENTOURS,
    areas: [
      ZONE_AREA_LABELS.BROSSARD,
      ZONE_AREA_LABELS.SAINT_HUBERT,
      ZONE_AREA_LABELS.BOUCHERVILLE,
      ZONE_AREA_LABELS.SAINT_LAMBERT,
      ZONE_AREA_LABELS.GREENFIELD_PARK,
    ],
  },
  {
    region: ZONE_REGION_LABELS.LAVAL_ET_ALENTOURS,
    areas: [
      ZONE_AREA_LABELS.CHOMEDEY,
      ZONE_AREA_LABELS.SAINTE_ROSE,
      ZONE_AREA_LABELS.VIMONT,
      ZONE_AREA_LABELS.PONT_VIAU,
      ZONE_AREA_LABELS.DUVERNAY,
    ],
  },
  {
    region: ZONE_REGION_LABELS.REPENTIGNY_ET_ALENTOURS,
    areas: [
      ZONE_AREA_LABELS.LASSOMPTION,
      ZONE_AREA_LABELS.LE_GARDEUR,
      ZONE_AREA_LABELS.CHARLEMAGNE,
      ZONE_AREA_LABELS.MASCOUCHE,
      ZONE_AREA_LABELS.TERREBONNE,
    ],
  },
];

export const ZONE_ROUTE_BY_REGION_LABEL: Record<ZONE_REGION_LABELS, string> = {
  [ZONE_REGION_LABELS.MONTREAL]: ROUTE_PATHS.MONTREAL,
  [ZONE_REGION_LABELS.LONGUEUIL_ET_ALENTOURS]: ROUTE_PATHS.LONGUEUIL,
  [ZONE_REGION_LABELS.LAVAL_ET_ALENTOURS]: ROUTE_PATHS.LAVAL,
  [ZONE_REGION_LABELS.REPENTIGNY_ET_ALENTOURS]: ROUTE_PATHS.REPENTIGNY,
};

export const ZONE_ROUTE_BY_AREA_LABEL: Record<ZONE_AREA_LABELS, string> = {
  [ZONE_AREA_LABELS.PLATEAU_MONT_ROYAL]: ROUTE_PATHS.MONTREAL,
  [ZONE_AREA_LABELS.ROSEMONT]: ROUTE_PATHS.MONTREAL,
  [ZONE_AREA_LABELS.AHUNTSIC]: ROUTE_PATHS.MONTREAL,
  [ZONE_AREA_LABELS.SAINT_LEONARD]: ROUTE_PATHS.MONTREAL,
  [ZONE_AREA_LABELS.VILLE_MARIE]: ROUTE_PATHS.MONTREAL,
  [ZONE_AREA_LABELS.BROSSARD]: ROUTE_PATHS.LONGUEUIL,
  [ZONE_AREA_LABELS.SAINT_HUBERT]: ROUTE_PATHS.LONGUEUIL,
  [ZONE_AREA_LABELS.BOUCHERVILLE]: ROUTE_PATHS.LONGUEUIL,
  [ZONE_AREA_LABELS.SAINT_LAMBERT]: ROUTE_PATHS.LONGUEUIL,
  [ZONE_AREA_LABELS.GREENFIELD_PARK]: ROUTE_PATHS.LONGUEUIL,
  [ZONE_AREA_LABELS.CHOMEDEY]: ROUTE_PATHS.LAVAL,
  [ZONE_AREA_LABELS.SAINTE_ROSE]: ROUTE_PATHS.LAVAL,
  [ZONE_AREA_LABELS.VIMONT]: ROUTE_PATHS.LAVAL,
  [ZONE_AREA_LABELS.PONT_VIAU]: ROUTE_PATHS.LAVAL,
  [ZONE_AREA_LABELS.DUVERNAY]: ROUTE_PATHS.LAVAL,
  [ZONE_AREA_LABELS.LASSOMPTION]: ROUTE_PATHS.REPENTIGNY,
  [ZONE_AREA_LABELS.LE_GARDEUR]: ROUTE_PATHS.REPENTIGNY,
  [ZONE_AREA_LABELS.CHARLEMAGNE]: ROUTE_PATHS.REPENTIGNY,
  [ZONE_AREA_LABELS.MASCOUCHE]: ROUTE_PATHS.REPENTIGNY,
  [ZONE_AREA_LABELS.TERREBONNE]: ROUTE_PATHS.REPENTIGNY,
};

export const MAJOR_ZONE_LINKS = [
  { label: ZONE_REGION_LABELS.MONTREAL, path: ROUTE_PATHS.MONTREAL },
  { label: ZONE_REGION_LABELS.LAVAL_ET_ALENTOURS, path: ROUTE_PATHS.LAVAL },
  { label: ZONE_REGION_LABELS.LONGUEUIL_ET_ALENTOURS, path: ROUTE_PATHS.LONGUEUIL },
  { label: ZONE_REGION_LABELS.REPENTIGNY_ET_ALENTOURS, path: ROUTE_PATHS.REPENTIGNY },
] as const;

export const STRUCTURED_DATA_AREA_SERVED: AREA_SERVED_LABELS[] = [
  AREA_SERVED_LABELS.MONTREAL,
  AREA_SERVED_LABELS.LAVAL,
  AREA_SERVED_LABELS.LONGUEUIL,
  AREA_SERVED_LABELS.RIVE_SUD,
  AREA_SERVED_LABELS.REPENTIGNY,
];

export const CONTACT_AREA_SERVED_LINE_1 = `${AREA_SERVED_LABELS.MONTREAL}, ${AREA_SERVED_LABELS.LAVAL}, ${AREA_SERVED_LABELS.LONGUEUIL}, ${AREA_SERVED_LABELS.SAINTE_JULIE}`;
export const CONTACT_AREA_SERVED_LINE_2 = `${AREA_SERVED_LABELS.RIVE_SUD} et les environs`;

export const CONTACT_AREA_SERVED_SUMMARY = `${AREA_SERVED_LABELS.MONTREAL}, ${AREA_SERVED_LABELS.LAVAL}, ${AREA_SERVED_LABELS.LONGUEUIL}, ${AREA_SERVED_LABELS.SAINTE_JULIE} et la ${AREA_SERVED_LABELS.RIVE_SUD}`;
